const $=id=>document.getElementById(id),v=$('video'),all=[],duration=DATA.t.at(-1)+1/DATA.fps;
const rounds=DATA.segments||[{start:0,end:duration,title:'Local arena',A:'BLACK KIT',B:'WHITE KIT'}],roundAt=t=>{const k=rounds.findIndex(s=>t>=s.start&&t<s.end);return k<0?rounds.length-1:k},roundName=k=>'ROUND '+String(k+1).padStart(2,'0');
rounds.forEach((s,k)=>all.push({t:s.start,type:roundName(k)+' START',who:s.A+' vs '+s.B,source:s.title}));
const winA=DATA.win_A||[],winPts=DATA.win_points||[],pct=x=>Math.round(x*100);
winPts.forEach(p=>all.push({t:p.t,type:'WIN PROB UPDATE',who:'A '+pct(p.A)+'% / B '+(100-pct(p.A))+'%',source:'Luna Decisions'}));
let lastFlash=null;
for(let i=0;i<DATA.t.length;i++){
 if(DATA.engaged[i]!==null&&(i===0||DATA.engaged[i]!==DATA.engaged[i-1]))all.push({t:DATA.t[i],type:DATA.engaged[i]?'ENGAGEMENT START':'ENGAGEMENT END',who:'A / B',source:'existing rule'});
 for(const who of ['A','B'])if(DATA['ext_'+who][i]!=null&&DATA['ext_'+who][i]>=.9&&(i===0||DATA['ext_'+who][i-1]==null||DATA['ext_'+who][i-1]<.9))all.push({t:DATA.t[i],type:'PUNCH CANDIDATE',who,source:'extension ≥ 0.9'});
}
all.sort((a,b)=>a.t-b.t);
const fmt=x=>x==null?'—':x.toFixed(2);let prev=-1,visibleCount=-1;
function update(){const t=v.currentTime,i=Math.min(DATA.t.length-1,Math.max(0,Math.round(t*DATA.fps)));$('seek').value=t;const k=roundAt(t),seg=rounds[k];$('clock').textContent=String(Math.max(0,Math.ceil(seg.end-t))).padStart(2,'0');$('round').textContent=roundName(k);$('arena').textContent=seg.title.toUpperCase()+' / '+roundName(k);$('kitA').textContent='PLAYER 01 / '+seg.A;$('kitB').textContent=seg.B+' / PLAYER 02';$('time').textContent=t.toFixed(2)+' / '+duration.toFixed(2);$('play').textContent=v.paused?'▶ Play':'Ⅱ Pause';if(i===prev)return;prev=i;
 const engaged=DATA.engaged[i],known=engaged!=null;$('state').textContent=!known?'UNKNOWN':engaged?'ENGAGE!':'CLEAR';$('stateText').textContent=!known?'Insufficient data':engaged?'Exchange active · Stay alert':'Current rule: no engagement';$('callout').classList.toggle('hot',!!engaged);$('risk').textContent=!known?'Tracking uncertain':engaged?'Engagement alert':'Alert cleared';$('light').style.color=!known?'#888':engaged?'#ff6552':'#89e39e';
 const wa=winA[i],pts=winPts.filter(p=>p.t>=seg.start&&p.t<=t+1e-6),wLast=pts.at(-1),wPrev=pts.at(-2);$('wpA').textContent=wa==null?'—':pct(wa)+'%';$('wpB').textContent=wa==null?'—':(100-pct(wa))+'%';$('wpFill').style.width=(wa==null?50:wa*100)+'%';document.querySelector('.wp-bar').classList.toggle('empty',wa==null);$('wpStatus').textContent=!wLast?'No estimate yet this round':t-wLast.t<1.05?'Updated at '+wLast.t.toFixed(1)+'s · engaged second':'Held since '+wLast.t.toFixed(1)+'s · no engagement, not sampled';$('wpTrend').textContent=wLast&&wPrev?'A '+(pct(wLast.A)-pct(wPrev.A)>=0?'+':'')+(pct(wLast.A)-pct(wPrev.A))+' pts':'';if(wLast&&wLast!==lastFlash){lastFlash=wLast;const w=document.querySelector('.winprob');w.classList.add('flash');setTimeout(()=>w.classList.remove('flash'),500)}
 const visible=all.filter(e=>e.t<=t),punch=visible.filter(e=>e.type==='PUNCH CANDIDATE'&&e.t>=seg.start);
 for(const who of ['A','B']){const reach=DATA['reach_'+who][i],ext=DATA['ext_'+who][i];const p=reach==null||ext==null?0:Math.round(Math.min(1,Math.max(0,1-reach/1.5)) * ext*100);$('bar'+who).style.width=p+'%';$('pressure'+who).textContent=reach==null||ext==null?'—':p;$('count'+who).textContent=String(punch.filter(e=>e.who===who).length).padStart(2,'0');}
 const last=punch.at(-1);$('move').textContent=last?last.who+' · Punch candidate / '+last.t.toFixed(2)+'s':'Waiting for an action';
 $('metrics').innerHTML=[['A win prob','win_A'],['Center distance','com_dist'],['A reach','reach_A'],['B reach','reach_B'],['A extension','ext_A'],['B extension','ext_B']].map(([label,key])=>'<div class="metric">'+label+'<strong>'+fmt(DATA[key][i])+'</strong></div>').join('');
 $('record').textContent=JSON.stringify({clip:DATA.clip,round:roundName(k),A:seg.A,B:seg.B,frame:i,t_s:DATA.t[i],engaged:DATA.engaged[i],win_A:winA[i]??null,com_dist:DATA.com_dist[i],reach_A:DATA.reach_A[i],reach_B:DATA.reach_B[i],ext_A:DATA.ext_A[i],ext_B:DATA.ext_B[i],source:'offline YOLO measurements'},null,2);
 if(visible.length!==visibleCount){visibleCount=visible.length;$('events').replaceChildren(...visible.slice().reverse().map(e=>{const tr=document.createElement('tr');for(const value of [e.t.toFixed(2)+'s',e.type,e.who,e.source]){const td=document.createElement('td');td.textContent=value;tr.append(td)}tr.tabIndex=0;tr.onclick=()=>{v.currentTime=e.t;update()};tr.onkeydown=k=>{if(k.key==='Enter')tr.click()};return tr}));}
}
$('play').onclick=()=>{if(v.paused)v.play().catch(()=>{$('stateText').textContent='Please press play again'});else v.pause()};$('reset').onclick=()=>{v.currentTime=0;update()};$('seek').oninput=e=>{v.currentTime=+e.target.value;update()};v.addEventListener('loadedmetadata',()=>{$('seek').max=v.duration;update()});v.addEventListener('seeked',update);v.addEventListener('play',()=>{prev=-1;update()});v.addEventListener('pause',()=>{prev=-1;update()});
function mode(back){document.body.classList.toggle('backend',back);$('console').hidden=!back;$('audience').classList.toggle('selected',!back);$('database').classList.toggle('selected',back);history.replaceState(null,'',back?'#database':'#audience')}$('audience').onclick=()=>mode(false);$('database').onclick=()=>mode(true);mode(location.hash==='#database');
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({clip:DATA.clip,source:'offline replay',rounds,events:all},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fightlens-events.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};function loop(){update();requestAnimationFrame(loop)}loop();
